/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yayan' at '6/5/18 9:05 PM' with Gradle 2.7
 *
 * @author yayan, @date 6/5/18 9:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
